version: '3.1'
services:
  stats-server:
    build: ./stats_service/stats-server
    image: stats_server
    container_name: ewm-server
    #restart: on-failure
    ports:
      - "9090:9090"
      - "9091:9092"
    depends_on:
      - stats-db
    environment:
      - DB_NAME=stats
      - DB_HOST=stats-db
      - DB_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9092

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  ewm-service:
    build: ./main_service
    container_name: ewm_main_service
    #restart: on-failure
    ports:
      - "8080:8080"
      - "8081:8082"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - STATS_SERVER=http://stats-server:9090
      - DB_NAME=ewm
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8082

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6540:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
